spring:
  application:
    name: auth-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/ewallet-realm

server:
  port: 8888

keycloak:
  admin-client:
    server-url: http://localhost:9999
    realm: ewallet-realm
    client-id: ewallet-auth-service-client
    client-secret: fe12FBYR5E8yHRcaD6vwRyKWrUEN7ZPd

token:
  expiration:
    access-token: 300
    refresh-token: 1800

logging:
  level:
    org.springframework.security: TRACE
