spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: http://localhost:8888
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: profile-service
              uri: http://localhost:8082
              predicates:
                - Path=/profile/**
              filters:
                - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/ewallet-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
