server:
  port: 8888
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service

  output:
    ansi:
      enabled: ALWAYS

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/ewallet-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true

keycloak:
  admin-client:
    server-url: http://localhost:9999
    realm: ewallet-realm
    client-id: ewallet-auth-service-client
    client-secret: ${KEYCLOAK_CLIENT_SECRET:fe12FBYR5E8yHRcaD6vwRyKWrUEN7ZPd}

token:
  expiration:
    access-token: 300
    refresh-token: 1800

logging:
  level:
    org.springframework.cloud.gateway: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
