spring:
  application:
    name: wallet-service

  output:
    ansi:
      enabled: ALWAYS # Luôn in màu trên console

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

    # PostgreSQL configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/ewallet-realm

  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: localhost:19092

    properties:
      schema.registry.url: http://localhost:7878
      specific.avro.reader: true

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      retries: 3

      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1

    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer

        schema.registry.url: http://localhost:7878
        specific.avro.reader: true

        spring.deserializer.value.delegate.not.null: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true

server:
  port: 8085

logging:
  level:
    org.springframework.security: TRACE
