services:
  postgres:
    image: postgres:16-alpine
    command: ["postgres", "-c", "shared_buffers=128MB", "-c", "max_connections=100"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 256M

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 9999
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      # KHÓA CHỐT: Ép Keycloak chạy trong 512MB
      JAVA_OPTS_APPEND: "-Xms128m -Xmx512m -XX:MaxMetaspaceSize=128m"
    ports:
      - "9999:8080"
    restart: always
    depends_on:
      - postgres
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 640M

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 64M

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:19092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"

      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_HEAP_OPTS: "-Xms512M -Xmx512M"
    volumes:
      - volume_kafka_data:/var/lib/kafka/data
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1G

  kafka-ui-service:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-service
    ports:
      - "7777:8080"
    restart: unless-stopped
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      JAVA_OPTS: "-Xmx128M"
    depends_on:
      - kafka
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 150M

  schema-registry-service:
    image: confluentinc/cp-schema-registry:7.4.4
    container_name: schema-registry-service
    restart: always
    ports:
      - "7878:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
    depends_on:
      - kafka
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M

  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: mongod --wiredTigerCacheSizeGB 0.25 # Giới hạn bộ nhớ cache của MongoDB để giảm sử dụng RAM
    ports:
      - "27017:27017"
    restart: always
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  postgres_data:
    external: true
    name: ewallet-microservices_postgres_data
  redis_data:
    external: true
    name: ewallet-microservices_redis_data
  volume_kafka_data:
    external: true
    name: ewallet-microservices_volume_kafka_data
  mongodb_data:
    name: ewallet-microservices_volume_mongodb_data

networks:
  app-network:
    driver: bridge
