server:
  port: 8084

spring:
  application:
    name: transaction-service

  output:
    ansi:
      enabled: ALWAYS

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

    # PostgreSQL configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

    # MongoDB configuration
  mongodb:
    uri: mongodb://localhost:27017/transaction_db

  # Enable virtual threads for better concurrency
  threads:
    virtual:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/ewallet-realm

  kafka:
    bootstrap-servers: localhost:19092
    schema-registry-url: http://localhost:7878
    specific-avro-reader: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
